version: '3'
services:
  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
      GF_PATHS_CONFIG: /custom_config/grafana.ini
    volumes:
      - /var/lib/grafana
      - .:/var/lib/grafana/plugins/cassandra
      - ./config/:/custom_config/
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./test_data.cql:/test_data.cql
